name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: write

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

  release:
    name: Create GitHub Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release zip archive
        run: |
          cd custom_components/private_repo_syncer
          zip private_repo_syncer.zip -r ./
          mv private_repo_syncer.zip ../../

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: private_repo_syncer.zip
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}
